language: rust
rust:
  - nightly
  - beta
  - stable
script: |
  cargo build --verbose &&
  cargo test --verbose &&
  ([ $TRAVIS_RUST_VERSION != nightly ] || cargo check --verbose --no-default-features) &&
  ([ $TRAVIS_RUST_VERSION != nightly ] || cargo test --verbose --features union) &&
  ([ $TRAVIS_RUST_VERSION != nightly ] || cargo bench --verbose --bench bench)
  ([ $TRAVIS_RUST_VERSION != nightly ] || cargo bench -v --features serde --bench serde)
notifications:
  webhooks: http://build.servo.org:54856/travis
